# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20170729_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='article_counts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
