# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20170729_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecategory',
            old_name='article_counts',
            new_name='article_number',
        ),
    ]
