# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20171228_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
