# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-09 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20180101_1414'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlecategory',
            table='categories',
        ),
    ]
