# Generated by Django 2.2.10 on 2020-03-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20200112_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
