# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_category', '0004_auto_20171022_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecategory',
            old_name='category_name',
            new_name='name',
        ),
    ]
