# Generated by Django 2.1.5 on 2019-01-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_auto_20180608_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_time',)},
        ),
    ]
