#!/bin/bash

set -o errexit

# create volumes's source before build images,
# otherwise PermissionError or FileNotFoundError occurs 
# when container runs.

mkdir -p var/log run data captcha markdown

if [ -e "./postgresql" ]
then
    sudo chown -R "${USER}":"${USER}" ./postgresql;
fi

cp -ruv ./backend/static "$HOME"         # copy static files, such as js, css and images
docker-compose -f local.yml up "$@"     # start building images
