#!/bin/bash

set -xe

# create volumes's source before build images,
# otherwise PermissionError or FileNotFoundError occurs 
# when container start running.

mkdir -p var/log run data captcha markdown assets

if [ -e "./postgresql" ]
then
    sudo chown -R "${USER}":"${USER}" ./postgresql;
fi

docker-compose -f production.yml up "$@"
cp -ruv assets frontend/public/assets "$HOME"
