#!/bin/bash

set -xe

# create volumes's source before build images,
# otherwise PermissionError or FileNotFoundError occurs 
# when container start running.


mkdir -p var/log run data captcha markdown dj_assets "$HOME/assets/"

if [ -e "./postgresql" ]
then
    sudo chown -R "${USER}":"${USER}" ./postgresql;
fi

docker-compose -f production.yml up "$@"
cp -ruv dj_assets/* "$HOME/assets/"
cp -ruv ./frontend/public/* "$HOME/assets/"
