# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecategory',
            old_name='category_counts',
            new_name='article_counts',
        ),
    ]
