# Generated by Django 2.1.5 on 2019-01-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20180928_0230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
