# Generated by Django 2.2.6 on 2020-01-07 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20190117_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ('created_time',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
