# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20180608_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
