#!/bin/bash

set -e errexit

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${PG_USER} WITH LOGIN PASSWORD '${PG_USER_PASSWORD}';
    CREATE DATABASE ${PG_USER_DB} OWNER ${PG_USER} ENCODING 'UTF8';
    GRANT ALL PRIVILEGES ON DATABASE ${PG_USER} TO  ${PG_USER};
EOSQL
