# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170606_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateField(auto_now=True),
        ),
    ]
