# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-09 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
