# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-10 16:19
from __future__ import unicode_literals

from django.db import migrations, models

import apps.article.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=apps.article.models.default_slug, max_length=100, null=True, unique=True),
        ),
    ]
