# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, default='untagged', help_text='使用逗号分隔', max_length=64),
        ),
    ]
