# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170606_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.AlterField(
            model_name='article',
            name='view_times',
            field=models.IntegerField(default=0),
        ),
    ]
