# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_summary',
        ),
    ]
