#!/bin/bash

set -o errexit

GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NOCOLOR='\033[0m'

if [ -e './run' ]
then
    rm -f ./run/*
fi

postgres_ready() {
python << END
import sys
import psycopg2


try:
    conn = psycopg2.connect(
        dbname='${POSTGRES_DB}',
        user='${POSTGRES_USER}',
        password='${POSTGRES_PASSWORD}',
        host='${POSTGRES_HOST}',
        port=${POSTGRES_PORT},
    )
    cursor = conn.cursor()
    cursor.execute("SELECT 'Hello, PostgreSQL!'")
    sys.stdout.write('${GREEN}' + cursor.fetchone()[0] + '${NOCOLOR}\n')
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}

until postgres_ready; do
    >&2 echo -e "${YELLOW}Waiting for PostgreSQL to be available.....${NOCOLOR}"
    sleep 1
done
>&2 echo -e "${GREEN}PostgreSQL is available!!!${NOCOLOR}"

exec "$@"
