#!/bin/bash

set -o errexit

if [ -e './run' ]
then
    rm -f ./run/*
fi

mysql_ready() {
python << END
import sys
import MySQLdb


try:
    MySQLdb.connect(
        db='${MYSQL_DATABASE}',
        host='${MYSQL_HOST}',
        port=${MYSQL_PORT},
        user='${MYSQL_USER}',
        password='${MYSQL_PASSWORD}'
    )
except MySQLdb.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}

until mysql_ready; do
    >&2 echo "Waiting for MySQL to be available....."
    sleep 1
done
>&2 echo "MySQL is available!!!"


exec "$@"
