#!/bin/bash

set -o errexit

if [ -e './celeryd.pid' ]
then
    rm -f ./celeryd.pid
fi

if [ ! -d './log' ]
then
    mkdir log
    touch log/mysite.log
fi

if [ ! -d './data' ]
then
    mkdir data
fi

mysql_ready() {
python << END
import sys
import MySQLdb


try:
    MySQLdb.connect(
        db='blog',
        host='mysql',
        port=3306,
        user='blog',
        password='123456'
    )
except MySQLdb.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}

until mysql_ready; do
    >&2 echo "Waiting for MySQL to be available....."
    sleep 1
done
>&2 echo "MySQL is available!!!"


exec "$@"
