# Generated by Django 2.2.6 on 2020-01-12 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_auto_20200107_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
