# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171125_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='Designates whether the user                                    will be blocked', verbose_name='validation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user                                     should be treated as active. Unselect this                                     instead of deleting accounts.', verbose_name='active'),
        ),
    ]
