# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171128_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_valid',
            field=models.BooleanField(default=False, help_text='Designates whether the user                                    will be blocked', verbose_name='validation'),
        ),
    ]
