# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-09 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171215_0721'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='auth_users',
        ),
    ]
