# Generated by Django 2.2.6 on 2020-01-12 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
