# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_summary',
        ),
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='view_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
