# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-19 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20181018_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, default='untagged', help_text='使用逗号分隔', max_length=32),
        ),
    ]
