# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20180105_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_reply',
        ),
    ]
