# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_comment_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.IntegerField(),
        ),
    ]
