# Generated by Django 2.1.9 on 2019-07-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190117_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this site', verbose_name='staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_valid',
            field=models.BooleanField(default=False, help_text='Designates whether the user will be blocked', verbose_name='validation'),
        ),
    ]
