# Generated by Django 2.2.6 on 2020-01-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20190117_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='view_times',
            new_name='user_view_times',
        ),
        migrations.AddField(
            model_name='article',
            name='page_view_times',
            field=models.PositiveIntegerField(default=0)
        )
    ]
