# Generated by Django 2.2.8 on 2020-01-13 15:15

import apps.article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20200112_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=apps.article.models.default_slug, max_length=100, unique=True),
        ),
    ]
